---
name: vue3_migrate_organizations_cd
description: Enables Vue 3 in compatibility mode for the organization continuous deployment (CD) SPA.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/629041
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/255462
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/629041
milestone: '19.5'
group: group::environments
type: beta
default_enabled: false
